#spring:
#  data:
#    elasticsearch:
#      cluster-nodes: 192.168.255.106:9300
#      cluster-name: icourtcluster
#      local: false
#
#  datasource:
#      url: jdbc:mysql://192.168.255.2/alpha_60?useUnicode=true&amp;characterEncoding=utf8&amp;autoReconnect=true&amp;zeroDateTimeBehavior=convertToNull&amp;allowMultiQueries=true
#      username: alpha_dev
#      password: EJ82fVcH3h!K
#      driverClassName : com.mysql.jdbc.Driver
#
#server:
#  port: 8090
#  session-timeout: 30
#  tomcat.max-threads: 0
#  tomcat.uri-encoding: UTF-8
#
#
#
#mybatis:
#  type-aliases-package: com.icourt.cart.dao
#  mapper-locations: mapper/*.xml
#
